# Generated by Django 5.0.6 on 2024-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_users_membership_and_more'),
        ('users', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisations',
            field=models.ManyToManyField(related_name='user_organisations', through='organisation.Membership', to='organisation.organisation'),
        ),
    ]
