# Generated by Django 5.0.6 on 2024-07-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userId',
        ),
    ]
