# Generated by Django 5.0.6 on 2024-07-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_users_membership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='org_id',
            new_name='orgId',
        ),
    ]
